# doc_loader.py

import os

VISA_DIRECT_KNOWLEDGE = """
============================================
VISA DIRECT API - COMPLETE KNOWLEDGE BASE
============================================

--- OVERVIEW ---
Visa Direct is a real-time push payments platform that enables fund transfers directly to Visa debit, prepaid, and eligible credit cards globally.
Base URL (Sandbox): https://sandbox.api.visa.com
Base URL (Production): https://api.visa.com

--- AUTHENTICATION & HEADERS ---
Visa Direct uses Mutual TLS (mTLS) combined with specific HTTP Headers.
Required credentials:
- Client Certificate (.pem file)
- Private Key (.pem file)
- Basic Auth: User ID and Password (for some older endpoints, though API key is standard)

Required Headers:
- x-pay-token: Used for authentication in some Visa developer endpoints.
- x-correlation-id: (Optional but recommended) Unique identifier for the transaction request, generated by the client to trace requests.
- Content-Type: application/json

--- IDEMPOTENCY ---
Visa Direct APIs do not natively support an Idempotency-Key header. Instead, idempotency is handled via the `systemsTraceAuditNumber` (STAN) and `retrievalReferenceNumber` (RRN).
- STAN must be a unique 6-digit number per day per endpoint.
- RRN must be a 12-character unique string per transaction.
Submitting the exact same STAN and RRN within the same 24-hour period will result in a duplicate transaction error or return the original response.

--- RATE LIMITING & THROTTLING ---
- Visa Direct does not explicitly publish universal rate limits, but sandbox environments are heavily throttled (typically ~10-50 TPS).
- Production rate limits are negotiated during the certification process.
- If rate-limited, you will receive HTTP 429 Too Many Requests. Implement exponential backoff for retries.

--- FUND TRANSFER (pushFundsTransactions) ---
Endpoint: POST /visadirect/fundstransfer/v1/pushfundstransactions

Required fields:
- systemsTraceAuditNumber: unique 6-digit int
- retrievalReferenceNumber: 12 char string (format: YDDDHHNNNNNN)
- localTransactionDateTime: YYYY-MM-DDTHH:MM:SS
- amount: integer or string (in cents or formatted strictly as string depending on SDK, usually string with decimals e.g., "100.00")
- senderCurrencyCode: e.g. "USD"
- senderPrimaryAccountNumber: sender card number
- recipientPrimaryAccountNumber: receiver card
- businessApplicationId: "AA" (account to account), "PP" (P2P), "FD" (Fund Disbursement)
- cardAcceptor: dict with name, terminalId, idCode, address (county, country, state, zipCode)

--- TRANSACTION STATUS CHECK ---
Endpoint: GET /visadirect/fundstransfer/v1/pushfundstransactions/{statusIdentifier}

--- REVERSE FUND TRANSFER ---
Endpoint: POST /visadirect/fundstransfer/v1/reversefundstransactions
Used to cancel or reverse a transaction that has not been settled.
Requires `originalDataElements` containing the STAN and date of the original push.

--- VISA ALIAS DIRECTORY ---
The Visa Alias Directory service allows customers to send and receive payments using an alias (like an email address or mobile phone number) instead of a Primary Account Number (PAN).

Endpoint to Resolve Alias: GET /visaaliasdirectory/v1/resolve/alias
Query parameters:
- aliasId: The mobile number or email
- aliasType: "01" for Phone Number, "02" for Email

Endpoint to Create Alias: POST /visaaliasdirectory/v1/manage/alias
Payload must contain the PAN, the alias, and consent details.

--- WATCHLIST SCREENING (AML/OFAC) ---
Visa provides the Watchlist Screening API to help comply with Anti-Money Laundering (AML) and Office of Foreign Assets Control (OFAC) regulations.
Endpoint: POST /watchlist/v1/screen
Payload:
- Name (First, Middle, Last)
- Address
- Date of Birth
- Reference ID
Response includes a `score` and `status` indicating the likelihood of a match against global watchlists. Transactions should be paused if a high-probability match occurs.

--- WEBHOOKS & NOTIFICATIONS ---
Visa Direct does not rely heavily on Webhooks for basic push/pull. You must actively poll the GET status endpoint or rely on the synchronous POST response. However, for specific batch processing, Visa offers a separate notification service that pushes to an exposed client endpoint.

--- ERROR CODES (COMPLETE) ---
Visa Direct uses ISO 8583 response codes (responseStatusCode).
- 00: Approved and completed successfully
- 03: Invalid merchant
- 04: Capture card
- 05: Do not honor (Generic decline from issuer)
- 12: Invalid transaction
- 13: Invalid amount
- 14: Invalid card number (no such number)
- 30: Format error
- 41: Lost card, pick up
- 43: Stolen card, pick up
- 51: Insufficient funds
- 54: Expired card
- 57: Transaction not permitted to cardholder
- 58: Transaction not permitted to terminal
- 61: Exceeds withdrawal amount limit
- 62: Restricted card
- 65: Exceeds withdrawal frequency limit
- 91: Issuer or switch is inoperative
- 96: System malfunction

HTTP Status Codes:
- 200 OK: Successful request
- 400 Bad Request: Validation error (check your payload)
- 401 Unauthorized: mTLS cert failure, invalid API key or Basic Auth
- 403 Forbidden: IP not whitelisted or lack of API permissions
- 500 Internal Server Error: Visa network error

--- IMPORTANT NOTES ---
- All amounts should be precise.
- systemsTraceAuditNumber must be unique per transaction per day.
- Always use sandbox for testing. Production keys require passing Visa's stringent certification process.
- mTLS certificates must be kept secure and rotated before expiration.
"""

def save_knowledge_base():
    os.makedirs("visa_docs", exist_ok=True)
    with open("visa_docs/visa_direct_kb.txt", "w") as f:
        f.write(VISA_DIRECT_KNOWLEDGE)
    print("Knowledge base saved.")

if __name__ == "__main__":
    save_knowledge_base()
